routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//site

Route::post('homeBusca','homeController@homeBusca')->name('homeBusca');
Route::get("/", "homeController@index")->name('home.index');
Route::get('home_detalhes/{id}', 'homeController@detalhes');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/uteis', 'HomeController@uteis')->name('uteis');
Route::get('/sabado', 'HomeController@sabado')->name('sabado');
Route::get('/domingo', 'HomeController@domingo')->name('domingo');

Route::get('/admin', function() {
    return view('admin.index');
})->middleware('auth');

Route::prefix('admin')->group(function () {
    
    Route::resource('horarios', 'Admin\HorarioController')->middleware('auth');
        Route::resource('tipos', 'Admin\TipoController')->middleware('auth');
        Route::resource('linhas', 'Admin\LinhaController')->middleware('auth');
Route::get('/horariosPDF', 'Admin\HorarioController@relatorio');
Route::get('horariosUC', 'Admin\HorarioController@horariosUC')->middleware('auth');
Route::get('horariosUB', 'Admin\HorarioController@horariosUB')->middleware('auth');    
Route::get('horariosSC', 'Admin\HorarioController@horariosSC')->middleware('auth');    
Route::get('horariosSB', 'Admin\HorarioController@horariosSB')->middleware('auth');    
Route::get('horariosDC', 'Admin\HorarioController@horariosDC')->middleware('auth');    
Route::get('horariosDB', 'Admin\HorarioController@horariosDB')->middleware('auth');    
    
    
});

Auth::routes();

resources/views/admin/horarios_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Horários')

@section('content_header')
 
    @if ($acao==1)
       <h2>Inclusão de Horários
    @elseif ($acao ==2)
       <h2>Alteração de Horários
    @endif          

    <a href="{{ route('horarios.index') }}" class="btn btn-primary pull-right"
       role="button">Voltar</a>
    </h2>

@endsection

@section('content')

   <div class="container-fluid">

    @if ($acao==1)
      <form method="POST" action="{{ route('horarios.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('horarios.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="col-sm-6">
        <div class="form-group">
          <label for="linhas_id">Nome da Linha</label>
          <select id="linhas_id" name="linhas_id" class="form-control">
            @foreach($linhas as $l)
              <option value="{{$l->id}}" 
                      {{ ((isset($reg) and $reg->linhas_id == $l->id) or 
                         old('linhas_id') == $l->id) ? "selected" : "" }}>
                      {{$l->nome}}</option>
            @endforeach
          </select>  
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="tipo_id">Tipo da Linha</label>
          <select id="tipo_id" name="tipo_id" class="form-control">
            @foreach($tipos as $t)
              <option value="{{$t->id}}" 
                      {{ ((isset($reg) and $reg->tipo_id == $t->id) or 
                         old('tipo_id') == $t->id) ? "selected" : "" }}>
                      {{$t->nome}}</option>
            @endforeach
          </select>  
        </div>
      </div>
                

    
      
        <div class="col-sm-6">
          <div class="form-group">
              <label for="horario">Horário (digite nesse formato: 2000-01-01 00:00:00)</label>
              <input type="text" id="horario" name="horario" required 
                     value="{{$reg->horario or old('horario')}}"
                     class="form-control">
          </div>
        </div>
    

    <div class="row">
        
      
        <div class="col-sm-4">
          <div class="form-group">
              <label for="sentido">Sentido</label>
              <select id="sentido" name="sentido" class="form-control">
                  @foreach($sent as $s)
                    <option value="{{$s}}"{{isset($reg) && $reg->sintido == $s || old('sentido') == $s ? "selected":""}}>{{$s}}</option>
                  @endforeach
              </select>  
            </div>
        </div>

       
        
      
        
    </div>
    <div class="col-sm-6">
        <div class="form-group">
        
          <select id="users-id" name="users_id" class="form-control" style="display:none">
            @foreach($users as $u)
              <option id="users-id" value="{{$u->id}}" >
                     </option>
            @endforeach
          </select>  
        </div>
      </div>

    <div class="col-sm-4">
    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">
    </div>
    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#horario').mask('####-##-## ##:##:##', {reverse: true});
    });
  </script>  
@endsection
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/horarios_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Horários')

@section('content_header')
    <h1>Cadastro de Horarios</h1>
    <h1>{{$informacao}}</h1>
   
    
   


    <a href="{{ route('horarios.create') }}" class="btn btn-primary pull-right"
       role="button">Novo</a>
    </h1>
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
      <th>Linha</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Hora</th>     
      <th>Sentido</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($linhas as $l)
      <tr>
        <td> {{$l->linha_id}} </td>
        <td> {{$l->tipo_id}} </td>
        <td> {{$l->descricao}} </td>
        <td> {{$l->horario }} </td>
        <td> {{$l->sentido }} </td>
          
       
        <td> 
            <a href="{{route('horarios.edit', $l->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
            <form style="display: inline-block"
                  method="post"
                  action="{{route('horarios.destroy', $l->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
       
        @if ($loop->iteration == $loop->count)
             <tr><td colspan=8>Total de Horarios cadastrados: {{$numHorarios}}                              
                              </td></tr>
        @endif        
    @empty
      <tr><td colspan=8> Não há Horários cadastrados ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $linhas->links() }}
@stop

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/horarios_rel.blade.php
  <div class="container-fluid">
 <h1 style="text-align: center">Horários</h1>
 
 
 <h2 style="text-align: center">Horários de Segunda a Sexta-feira</h2>
 <H3>
<span class="esquerda">CENTRO</span>
<span class="direita">BAIRRO</span>
</h3>

</DIV>

<body>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Linha</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Hora</th>     
      <th>Sentido</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($centroU as $c)
      <tr>
        <td> {{$c->nome}} </td>
        <td> {{$c->tipo_id}} </td>
        <td> {{$c->descricao}} </td>
        <td> {{$c->horario }} </td>
        <td> {{$c->sentido }} </td>
          
        @empty
        @endforelse
  </tbody>
</table>  

resources/views/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Horário')

@section('content_header')
    <h1>Página Principal</h1>


@stop

@section('content')
    <H4>Bem-Vindo {{ Auth::user()->name }}!</h4>
    <p>Área de Administração do Site</p>
@stop

resources/views/admin/linhas_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Linhas')

@section('content_header')
 
    @if ($acao==1)
       <h2>Inclusão de Linhas
    @elseif ($acao ==2)
       <h2>Alteração de Linhas
    @endif          

    <a href="{{ route('linhas.index') }}" class="btn btn-primary pull-right"
       role="button">Voltar</a>
    </h2>

@endsection

@section('content')

   <div class="container-fluid">

    @if ($acao==1)
      <form method="POST" action="{{ route('linhas.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('linhas.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="nome">Nome do Linha</label>
          <input type="text" id="nome" name="nome" required 
                 value="{{$reg->nome or old('nome')}}"
                 class="form-control">
        </div>
      </div>

      
    </div>              

    
      
       
    </div>

    <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="ano">Descrição</label>
            <input type="text" id="descricao" name="descricao" required 
                   value="{{$reg->descricao or old('descricao')}}"
                   class="form-control">
          </div>
        </div>
      
       

        <div class="col-sm-4">
          <div class="form-group">
            <label for="foto">Foto</label>
            <input type="file" id="foto" name="foto" required
                   class="form-control">
          </div>
        </div>
        
    </div>

    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">

    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  
@endsection
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/linhas_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Linhas')

@section('content_header')
    <h1>Cadastro de Linhas
    <a href="{{ route('linhas.create') }}" class="btn btn-primary pull-right"
       role="button">Novo</a>
    </h1>
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
       <th>Foto</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($linhas as $l)
      <tr>
        <td> {{$l->nome}} </td>
        <td> {{$l->descricao}} </td>
        <td>
          @if (Storage::exists($l->foto))
            <img src="{{url('storage/'.$l->foto)}}" 
                 style="width: 100px; height: 60px" alt="Foto">
          @else
            <img src="{{url('storage/fotos/semfoto.png')}}" 
                 style="width: 100px; height: 60px" alt="Foto">
         @endif
        </td>
        <td> 
            <a href="{{route('linhas.edit', $l->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
            <form style="display: inline-block"
                  method="post"
                  action="{{route('linhas.destroy', $l->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
        @if ($loop->iteration == $loop->count)
             <tr><td colspan=8>Total dos Linhas cadastradas: {{$numLinhas}}                              
                              </td></tr>
        @endif        
    @empty
      <tr><td colspan=8> Não há linhas cadastradas ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $linhas->links() }}
@stop

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/tipos_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Tipos')

@section('content_header')
 
    @if ($acao==1)
       <h2>Inclusão de Tipos
    @elseif ($acao ==2)
       <h2>Alteração de Tipos
    @endif          

    <a href="{{ route('tipos.index') }}" class="btn btn-primary pull-right"
       role="button">Voltar</a>
    </h2>

@endsection

@section('content')

   <div class="container-fluid">

    @if ($acao==1)
      <form method="POST" action="{{ route('tipos.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('tipos.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="nome">Tipo de dia da Semana</label>
          <input type="text" id="nome" name="nome" required 
                 value="{{$reg->nome or old('nome')}}"
                 class="form-control">
        </div>
      </div>

      
    </div>              

    
      
      

    <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="ano">Descrição</label>
            <input type="text" id="descricao" name="descricao" required 
                   value="{{$reg->descricao or old('descricao')}}"
                   class="form-control">
          </div>
        </div>
      
       

        
    </div>

    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">

    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  
@endsection

resources/views/admin/tipos_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Tipos')

@section('content_header')
    <h1>Cadastro de Tipos de dia da Semana
    <a href="{{ route('tipos.create') }}" class="btn btn-primary pull-right"
       role="button">Novo</a>
    </h1>
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($tipos as $t)
      <tr>
        <td> {{$t->nome}} </td>
        <td> {{$t->descricao}} </td>
        <td> {{date_format($t->created_at, 'd/m/Y')}} </td>
        <td> 
            <a href="{{route('tipos.edit', $t->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
            <form style="display: inline-block"
                  method="post"
                  action="{{route('tipos.destroy', $t->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
      
    @empty
      <tr><td colspan=8> Não há tipos cadastrados ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $tipos->links() }}
@stop

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection